### ISSUE TITLE
Symbol's value as variable is void: transient-current-prefix

### ISSUE THREAD

**Issue by amoghpj** [r0man/docopt.el#26]
Hey, thanks for this cool package!
I made a small script (https://github.com/amoghpj/inventory/blob/master/inventory.py) to play around with this. When invoked from the command line, the script works, so I don't think there is any docopt error. When I try to invoke it from docopt.el, the transient shows up, and I can specify usage patterns and set options, but if I choose any "Actions", emacs flashes this message in the minibuffer. toggle-debug-on-error doesn't help ,which leads me to think that this isn't raising an error? 
Emacs 26.1
Transient 0.1.0
Let me know if I'm doing something wrong. 
Thanks again, really excited about this package!

**Comment by r0man** [comment]
Hi @amoghpj,

I just tried your program on my machine and it works as
expected. I think you need a version of transient > 0.1.0.

I bumped the transient version in the package requires header to
0.3.0 now. Can you please try again?

Roman

**Comment by amoghpj** [comment]
Yup that was it, thanks for your time! 
Closing this issue.
