### ISSUE TITLE
Please don't require projectile in .dir-locals.el

### ISSUE THREAD

**Issue by akirak** [r0man/docopt.el#33]
Hello,

I tried to browse the source code of this project in Emacs, but it failed because I don't have `projectile` installed, which is required in your `.dir-locals.el`.

I would suggest you use the following snippet instead, which does nothing if projectile is unavailable:

```emacs-lisp
(when (require 'projectile nil t)
  (puthash (projectile-project-root) "make v=vvv test-buttercup" projectile-test-cmd-map))
```

**Comment by r0man** [comment]
Thanks for the suggestion. Fixed in https://github.com/r0man/docopt.el/pull/34
